app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('financas/', include('financas.urls')),
    path('contas/', include('contas.urls')),
]

financas/urls.py
from django.urls import path
from . import views
from .views import GerarRelatorioReceitas, GerarRelatorioDespesasFixas, GerarRelatorioDespesasVariaveis

urlpatterns = [
 

    # Receitas
    path('receitas/', views.ReceitaList.as_view(), name='receitas'),
    path('receitas/criar/', views.ReceitaCreate.as_view(), name='receita_criar'),
    path('receitas/<int:pk>/editar/', views.ReceitaUpdate.as_view(), name='receita_editar'),
    path('receitas/<int:pk>/deletar/', views.ReceitaDelete.as_view(), name='receita_deletar'),

    # Despesas Fixas
    path('despesas-fixas/', views.DespesaFixaList.as_view(), name='despesas_fixas'),
    path('despesas-fixas/criar/', views.DespesaFixaCreate.as_view(), name='despesa_fixa_criar'),
    path('despesas-fixas/<int:pk>/editar/', views.DespesaFixaUpdate.as_view(), name='despesa_fixa_editar'),
    path('despesas-fixas/<int:pk>/deletar/', views.DespesaFixaDelete.as_view(), name='despesa_fixa_deletar'),

    # Despesas Variáveis
    path('despesas-variaveis/', views.DespesaVariavelList.as_view(), name='despesas_variaveis'),
    path('despesas-variaveis/criar/', views.DespesaVariavelCreate.as_view(), name='despesa_variavel_criar'),
    path('despesas-variaveis/<int:pk>/editar/', views.DespesaVariavelUpdate.as_view(), name='despesa_variavel_editar'),
    path('despesas-variaveis/<int:pk>/deletar/', views.DespesaVariavelDelete.as_view(), name='despesa_variavel_deletar'),

    # Cartão de Crédito
    path('cartao-credito/', views.CartaoCreditoList.as_view(), name='cartao_credito'),
    path('cartao-credito/criar/', views.CartaoCreditoCreate.as_view(), name='cartao_credito_criar'),
    path('cartao-credito/<int:pk>/editar/', views.CartaoCreditoUpdate.as_view(), name='cartao_credito_editar'),
    path('cartao-credito/<int:pk>/deletar/', views.CartaoCreditoDelete.as_view(), name='cartao_credito_deletar'),

    # Totais
    path('totais/receitas/', views.TotalReceitasList.as_view(), name='total_receitas'),
    path('totais/despesas-fixas/', views.TotalDespesasFixasList.as_view(), name='total_despesas_fixas'),
    path('totais/despesas-variaveis/', views.TotalDespesasVariaveisList.as_view(), name='total_despesas_variaveis'),

    path('home/', views.HomeView.as_view(), name='home-page'),
    path('gerar-relatorio/receitas/', GerarRelatorioReceitas.as_view(), name='gerar_relatorio_receitas'),
    path('gerar-relatorio/despesas_fixas/', GerarRelatorioDespesasFixas.as_view(), name='gerar_relatorio_despesas_fixas'),
    path('gerar-relatorio/despesas_variaveis/', GerarRelatorioDespesasVariaveis.as_view(), name='gerar_relatorio_despesas_variaveis'),
]

financas/models.py
from django.utils import timezone
from django.db import models

class CartaoCredito(models.Model):
    nome = models.CharField('Nome', max_length=50)  # Corrigido max_digits
    limite = models.DecimalField('Limite', max_digits=10, decimal_places=2)
    

    def __str__(self):
        return self.nome

class Receita(models.Model):
    data = models.DateField('Data')
    valor = models.DecimalField('Valor', max_digits=10, decimal_places=2)
    descricao = models.CharField('Descrição', max_length=255)

    def __str__(self):
        return self.descricao

class DespesaFixa(models.Model):
    data = models.DateField('Data')
    valor = models.DecimalField('Valor', max_digits=10, decimal_places=2)
    descricao = models.CharField('Descrição', max_length=255)
    cartao_credito = models.ForeignKey(CartaoCredito, on_delete=models.CASCADE, null=True, blank=True)
    pago_com_cartao = models.BooleanField('Pago com cartão?', default=False)

    def __str__(self):
        return self.descricao

class DespesaVariavel(models.Model):
    data = models.DateField('Data')
    valor = models.DecimalField('Valor', max_digits=10, decimal_places=2)
    descricao = models.CharField('Descrição', max_length=255)
    cartao_credito = models.ForeignKey(CartaoCredito, on_delete=models.CASCADE, null=True, blank=True)
    pago_com_cartao = models.BooleanField('Pago com cartão?', default=False)

    def __str__(self):
        return self.descricao

class TotalReceitas(models.Model):
    total = models.DecimalField('Total', max_digits=10, decimal_places=2, default=0)
    data_criação = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-data_criação']


    def __str__(self):
        return f'Total: {self.total}'

class TotalDespesasFixas(models.Model):
    total = models.DecimalField('Total', max_digits=10, decimal_places=2, default=0)
    data_criação = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ['-data_criação']


    def __str__(self):
        return f'Total: {self.total}'

class TotalDespesasVariaveis(models.Model):
    total = models.DecimalField('Total', max_digits=10, decimal_places=2, default=0)
    data_criação = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-data_criação']


    def __str__(self):
        return f'Total: {self.total}'

financas/views.py
from  datetime import datetime
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import CartaoCredito, Receita, DespesaFixa, DespesaVariavel, TotalReceitas, TotalDespesasFixas, TotalDespesasVariaveis
from django.shortcuts import render
from django.views import View
from django.db.models import Sum
from django.http import HttpResponse
from reportlab.pdfgen import canvas # type: ignore
from io import BytesIO, StringIO
from django.utils import timezone
from financas.forms import ReceitaModelForm, DespesaFixaModelForm, DespesaVariavelModelForm, CartaoCreditoModelForm



class ReceitaList(ListView):
    model = Receita
    template_name = 'receita_list.html'
    context_object_name = 'receitas'

    def get_context_data(self, **kwargs):
           context = super().get_context_data(**kwargs)
           # Calcula o total de todas as receitas
           context['total_receitas'] = Receita.objects.aggregate(total=Sum('valor'))['total'] or 0
           return context

class ReceitaCreate(CreateView):
    model = Receita
    form_class  = ReceitaModelForm
    template_name = 'receita_create.html'
    success_url = reverse_lazy('receitas')

class ReceitaUpdate(UpdateView):
    model = Receita
    form_class  = ReceitaModelForm
    template_name = 'receita_update.html'
    success_url = reverse_lazy('receitas')

class ReceitaDelete(DeleteView):
    model = Receita
    template_name = 'receita_delete.html'
    success_url = reverse_lazy('receitas')


# Despesa Fixa
class DespesaFixaList(ListView):
    model = DespesaFixa
    template_name = 'despesa_fixa_list.html'
    context_object_name = 'despesas_fixas'

    def get_context_data(self, **kwargs):
           context = super().get_context_data(**kwargs)
           # Calcula o total de todas as receitas
           context['total_despesas_fixas'] = DespesaFixa.objects.aggregate(total=Sum('valor'))['total'] or 0
           return context


class DespesaFixaCreate(CreateView):
    model = DespesaFixa
    form_class = DespesaFixaModelForm
    template_name = 'despesa_fixa_create.html'
    success_url = reverse_lazy('despesas_fixas')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cartoes_credito'] = CartaoCredito.objects.all()
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user  # Associar despesa ao usuário logado
        return super().form_valid(form)

class DespesaFixaUpdate(UpdateView):
    model = DespesaFixa
    form_class  = DespesaFixaModelForm
    template_name = 'despesa_fixa_update.html'
    success_url = reverse_lazy('despesas_fixas')

class DespesaFixaDelete(DeleteView):
    model = DespesaFixa
    template_name = 'despesa_fixa_delete.html'
    success_url = reverse_lazy('despesas_fixas')

# Despesa Variável
class DespesaVariavelList(ListView):
    model = DespesaVariavel
    template_name = 'despesa_variavel_list.html'
    context_object_name = 'despesas_variaveis'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Calcula o total de todas as despesas variáveis
        context['total_despesa_variavel'] = DespesaVariavel.objects.aggregate(total=Sum('valor'))['total'] or 0
        
        return context

class DespesaVariavelCreate(CreateView):
    model = DespesaVariavel
    form_class = DespesaVariavelModelForm
    template_name = 'despesa_variavel_create.html'
    success_url = reverse_lazy('despesas_variaveis')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cartoes_credito'] = CartaoCredito.objects.all()
        return context

    def form_valid(self, form):
        # Assegura que a despesa variável está associada ao usuário atual
        form.instance.user = self.request.user
        return super().form_valid(form)

class DespesaVariavelUpdate(UpdateView):
    model = DespesaVariavel
    form_class = DespesaVariavelModelForm
    template_name = 'despesa_variavel_update.html'
    success_url = reverse_lazy('despesas_variaveis')

class DespesaVariavelDelete(DeleteView):
    model = DespesaVariavel
    template_name = 'despesa_variavel_delete.html'
    success_url = reverse_lazy('despesas_variaveis')


# Cartão de Crédito
class CartaoCreditoList(ListView):
    model = CartaoCredito
    template_name = 'cartao_credito_list.html'
    context_object_name = 'cartoes_credito'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        return context

class CartaoCreditoCreate(CreateView):
    model = CartaoCredito
    form_class  = CartaoCreditoModelForm
    template_name = 'cartao_credito_create.html'
    success_url = reverse_lazy('cartao_credito')

class CartaoCreditoUpdate(UpdateView):
    model = CartaoCredito
    form_class  = CartaoCreditoModelForm
    template_name = 'cartao_credito_update.html'
    success_url = reverse_lazy('cartao_credito')

class CartaoCreditoDelete(DeleteView):
    model = CartaoCredito
    template_name = 'cartao_credito_delete.html'
    success_url = reverse_lazy('cartao_credito')


# Totais
class TotalReceitasList(ListView):
    model = TotalReceitas
    template_name = 'total_receitas_list.html'

class TotalDespesasFixasList(ListView):
    model = TotalDespesasFixas
    template_name = 'total_despesas_fixas_list.html'

class TotalDespesasVariaveisList(ListView):
    model = TotalDespesasVariaveis
    template_name = 'total_despesas_variaveis_list.html'


class GerarRelatorioReceitas(View):
    def get(self, request, *args, **kwargs):
        data_inicio = request.GET.get('data_inicio')
        data_fim = request.GET.get('data_fim')

        # Se as datas de início e fim forem fornecidas, filtra as receitas
        if data_inicio and data_fim:
            data_inicio = datetime.strptime(data_inicio, '%Y-%m-%d').date()
            data_fim = datetime.strptime(data_fim, '%Y-%m-%d').date()
            receitas = Receita.objects.filter(data__range=(data_inicio, data_fim))
        else:
            # Caso contrário, pega todas as receitas
            receitas = Receita.objects.all()

        # Calcula o total das receitas
        total_receitas = receitas.aggregate(total=Sum('valor'))['total'] or 0

        return render(request, 'relatorio_receitas.html', {
            'receitas': receitas,  # Passa a lista de receitas
            'total_receitas': total_receitas,  # Passa o total das receitas
            'data_inicio': data_inicio,
            'data_fim': data_fim,
            'imprimir': False  # Para não mostrar o relatório automaticamente
        })

class GerarRelatorioDespesasFixas(View):
    def get(self, request, *args, **kwargs):
        data_inicio = request.GET.get('data_inicio')
        data_fim = request.GET.get('data_fim')

        if data_inicio and data_fim:
            data_inicio = datetime.strptime(data_inicio, '%Y-%m-%d').date()
            data_fim = datetime.strptime(data_fim, '%Y-%m-%d').date()
            despesas = DespesaFixa.objects.filter(data__range=(data_inicio, data_fim))
        else:
            despesas = DespesaFixa.objects.all()

        total_despesas = despesas.aggregate(total=Sum('valor'))['total'] or 0

        return render(request, 'relatorio_despesas_fixas.html', {
            'despesas': despesas,
            'total_despesas': total_despesas,
            'data_inicio': data_inicio,
            'data_fim': data_fim,
            'imprimir': False  # Para não mostrar o relatório automaticamente
        })


class GerarRelatorioDespesasVariaveis(View):
    def get(self, request, *args, **kwargs):
        data_inicio = request.GET.get('data_inicio')
        data_fim = request.GET.get('data_fim')

        if data_inicio and data_fim:
            data_inicio = datetime.strptime(data_inicio, '%Y-%m-%d').date()
            data_fim = datetime.strptime(data_fim, '%Y-%m-%d').date()
            despesas = DespesaVariavel.objects.filter(data__range=(data_inicio, data_fim))
        else:
            despesas = DespesaVariavel.objects.all()

        total_despesas = despesas.aggregate(total=Sum('valor'))['total'] or 0

        return render(request, 'relatorio_despesas_variavel.html', {
            'despesas': despesas,
            'total_despesas': total_despesas,
            'data_inicio': data_inicio,
            'data_fim': data_fim,
            'imprimir': False  # Para não mostrar o relatório automaticamente
        })


class HomeView(View):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        # Calculando o total de receitas
        total_receitas = Receita.objects.aggregate(total=Sum('valor'))['total'] or 0
        
        # Calculando os totais de despesas fixas e variáveis
        total_despesas_fixas = DespesaFixa.objects.aggregate(total=Sum('valor'))['total'] or 0
        total_despesas_variaveis = DespesaVariavel.objects.aggregate(total=Sum('valor'))['total'] or 0
        
        # Calculando o total de despesas
        total_despesas = total_despesas_fixas + total_despesas_variaveis
        
        # Calculando a diferença entre receitas e despesas
        diferenca = total_receitas - total_despesas
        diferenca_abs = abs(diferenca)  # Calculando o valor absoluto

        # Criando o contexto para passar para o template
        context = {
            'total_receitas': total_receitas,
            'total_despesas_fixas': total_despesas_fixas,
            'total_despesas_variaveis': total_despesas_variaveis,
            'diferenca': diferenca,
            'diferenca_abs': diferenca_abs,  # Passando o valor absoluto para o template
        }

        return render(request, self.template_name, context)

financas/templates/cartao_credito_create.html
{% extends 'base.html' %}

{% block title %}Criar Novo Cartão de Crédito{% endblock %}

{% block content %}
<div class="container mt-2">
    <div class="jumbotron text-center bg-light p-3 mb-5 shadow-sm rounded">
        <h1 class="display-6 text-primary">Crie um Novo Cartão de Crédito</h1>
        <hr class="my-4">
    </div>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <!-- Formulário de criação do cartão -->
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <h5 class="card-title">Informações do Cartão</h5>
                    <form method="post">
                        {% csrf_token %}
                        
                        <!-- Exibe os erros de validação, se houver -->
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                <ul>
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}

                        <!-- Renderiza os campos do formulário -->
                        <div class="form-group">
                            <label for="{{ form.nome.id_for_label }}">Nome do Cartão</label>
                            {{ form.nome }}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.limite.id_for_label }}">Limite do Cartão</label>
                            {{ form.limite }}
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                            <a href="{% url 'cartao_credito' %}" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

financas/templates/cartao_credito_delete.html
{% extends 'base.html' %}

{% block title %}Confirmar Exclusão{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="jumbotron text-center bg-light p-4 mb-4 shadow rounded">
        <h1 class="display-5 text-danger">Excluir Cartão</h1>
        <hr class="my-4">
        <p class="lead">Você tem certeza de que deseja excluir este cartão?</p>
        <p><strong>{{ object.descricao }}</strong></p>
    </div>
    
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
                            <a href="{% url 'cartao_credito' %}" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

financas/templates/cartao_credito_update.html
{% extends 'base.html' %}

{% block title %}Atualizar Cartão de Crédito{% endblock %}

{% block content %}
<div class="container mt-2">
    <div class="jumbotron text-center bg-light p-3 mb-5 shadow-sm rounded">
        <h1 class="display-6 text-primary">Atualizar Cartão de Crédito</h1>
        <hr class="my-4">
    </div>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <!-- Formulário de atualização do cartão -->
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <h5 class="card-title">Informações do Cartão</h5>
                    <form method="post">
                        {% csrf_token %}
                        
                        <!-- Exibe os erros de validação, se houver -->
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                <ul>
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}

                        <!-- Renderiza os campos do formulário com os dados do cartão -->
                        <div class="form-group">
                            <label for="{{ form.nome.id_for_label }}">Nome do Cartão</label>
                            {{ form.nome }}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.limite.id_for_label }}">Limite do Cartão</label>
                            {{ form.limite }}
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Atualizar</button>
                            <a href="{% url 'cartao_credito' %}" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

financas/templates/despesa_fixa_create.html
{% extends 'base.html' %}

{% block title %}Despesas Fixas{% endblock %}

{% block content %}
<div class="container mt-2">
    <div class="jumbotron text-center bg-light p-3 mb-5 shadow-sm rounded">
        <h1 class="display-6 text-primary">Adicione Aqui Suas Despesas Fixas</h1>
        <hr class="my-4">
    </div>
    
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <!-- Exemplo de formulário estilizado com Bootstrap -->
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <h5 class="card-title">Adicionar Despesa Fixa</h5>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_data">Data</label>
                            <input type="date" class="form-control" id="id_data" name="data" required>
                        </div>
                        <div class="form-group">
                            <label for="id_descricao">Descrição</label>
                            <input type="text" class="form-control" id="id_descricao" name="descricao" placeholder="Descrição da despesa" required>
                        </div>
                        <div class="form-group">
                            <label for="id_valor">Valor</label>
                            <input type="number" class="form-control" id="id_valor" name="valor" step="0.01" placeholder="0.00" required>
                        </div>
                        <div class="form-group">
                            <label for="id_cartao_credito">Cartão de Crédito</label>
                            <select class="form-control" id="id_cartao_credito" name="cartao_credito" required>
                                <option value="" disabled selected>Escolha o cartão</option>
                                {% for cartao in cartoes_credito %}
                                    <option value="{{ cartao.id }}">{{ cartao.nome }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="{% url 'despesas_fixas' %}" class="btn btn-secondary">Cancelar</a>
                        <!-- Certifique-se que 'despesas_fixas' corresponde ao nome correto -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

financas/templates/despesa_fixa_list.html
{% extends 'base.html' %}

{% block title %}Lista de Despesas Fixas{% endblock %}

{% block content %}

<div class="container mt-2">
    <h1 class="mb-4">Despesas Fixas</h1>
    <table class="table table-striped table-hover">
        <!-- Filtro por data -->
        <form method="GET" action="{% url 'gerar_relatorio_despesas_fixas' %}">
            <div class="row mb-3">
                <div class="col-md-3">
                    <label>Data Inicial:</label>
                    <input type="date" name="data_inicio" class="form-control">
                </div>
                <div class="col-md-3">
                    <label>Data Final:</label>
                    <input type="date" name="data_fim" class="form-control">
                </div>
                <div class="col-md-4 d-flex align-items-end">
                    <button type="submit" class="btn btn-primary">Filtrar</button>
                </div>
            </div>
        </form>
        <thead class="thead-dark">
            <tr>
                <th>Data</th>
                <th>Descrição</th>
                <th>Valor</th>
                <th>Cartão De Crédito</th>
                <th class="text-center">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for despesa_fixa in despesas_fixas %}
                <tr>
                    <td>{{ despesa_fixa.data }}</td>
                    <td>{{ despesa_fixa.descricao }}</td>
                    <td>R$ {{ despesa_fixa.valor|floatformat:2 }}</td>
                    <td>{{ despesa_fixa.cartao_credito.nome }}</td>
                    <td class="text-center">
                        <a href="{% url 'despesa_fixa_editar' despesa_fixa.pk %}" class="btn btn-outline-secondary btn-sm mr-1">
                            <i class="fas fa-edit"></i> Editar
                        </a>
                        <a href="{% url 'despesa_fixa_deletar' despesa_fixa.pk %}" class="btn btn-outline-danger btn-sm ml-1">
                            <i class="fas fa-trash-alt"></i> Deletar
                        </a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4" class="text-center">Nenhuma despesa fixa cadastrada cadastrada.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Exibir o somatório das receitas -->
    <div class="alert alert-info mt-1" role="alert">
        <strong>Somatório Total das Despesas Fixas:</strong> R$ {{ total_despesas_fixas|floatformat:2 }}
    </div>

    <div class="d-flex justify-content-between">
        <a href="{% url 'despesa_fixa_criar' %}" class="btn btn-primary">
          <i class="fas fa-plus"></i> Cadastrar Nova Depesa Fixa
        </a>
        <a href="{% url 'gerar_relatorio_despesas_fixas' %}" class="btn btn-primary ms-auto">
          Gerar Relatório de Despesas Fixas
        </a>
        
      </div>
</div>
{% endblock %}

financas/templates/despesa_fixa_update.html
{% extends 'base.html' %}

{% block title %}Editar Despesa Fixa{% endblock %}

{% block content %}
<div class="container mt-2">
    <div class="jumbotron text-center bg-light p-4 mb-5 shadow rounded">
        <h1 class="display-5 text-primary">Editar Despesa Fixa</h1>
        <hr class="my-4">
    </div>
    
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <h5 class="card-title mb-4">Atualizar Detalhes da Despesa Fixa</h5>
                    
                    <form method="post">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        
                        <div class="mb-3">
                            {{ form.data.label_tag }}
                            {{ form.data }}
                            <div class="text-danger">{{ form.data.errors }}</div>
                        </div>
                        
                        <div class="mb-3">
                            {{ form.descricao.label_tag }}
                            {{ form.descricao }}
                            <div class="text-danger">{{ form.descricao.errors }}</div>
                        </div>
                        
                        <div class="mb-3">
                            {{ form.valor.label_tag }}
                            {{ form.valor }}
                            <div class="text-danger">{{ form.valor.errors }}</div>
                        </div>
                        
                        <div class="mb-3">
                            {{ form.cartao_credito.label_tag }}
                            {{ form.cartao_credito }}
                            <div class="text-danger">{{ form.cartao_credito.errors }}</div>
                        </div>
                        
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary me-2">Salvar Alterações</button>
                            <a href="{% url 'despesas_fixas' %}" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

financas/templates/despesa_variavel_delete.html
{% extends 'base.html' %}

{% block title %}Confirmar Exclusão{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="jumbotron text-center bg-light p-4 mb-4 shadow rounded">
        <h1 class="display-5 text-danger">Excluir Despesa variável</h1>
        <hr class="my-4">
        <p class="lead">Você tem certeza de que deseja excluir esta despesa variável?</p>
        <p><strong>{{ object.descricao }}</strong></p>
    </div>
    
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
                            <a href="{% url 'despesas_fixas' %}" class="btn btn-secondary">Cancelar</a>
                            <!-- Certifique-se que 'despesas_fixas' corresponde ao nome correto -->
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

financas/templates/receita_create.html
{% extends 'base.html' %}

{% block title %}Nova Receita{% endblock %}

{% block content %}
<div class="container mt-2">
    <div class="jumbotron text-center bg-light p-3 mb-5 shadow-sm rounded">
        <h1 class="display-6 text-primary">Adicione Aqui Suas Receitas</h1>
       
        <hr class="my-4">
    </div>
    
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <!-- Exemplo de formulário estilizado com Bootstrap -->
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <h5 class="card-title">Adicionar Receita</h5>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_data">Data</label>
                            <input type="date" class="form-control" id="id_data" name="data" required>
                        </div>
                        <div class="form-group">
                            <label for="id_descricao">Descrição</label>
                            <input type="text" class="form-control" id="id_descricao" name="descricao" placeholder="Descrição da receita" required>
                        </div>
                        <div class="form-group">
                            <label for="id_valor">Valor</label>
                            <input type="number" class="form-control" id="id_valor" name="valor" step="0.01" placeholder="0.00" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="{% url 'receitas' %}" class="btn btn-secondary">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}